# Generated by Django 2.2.8 on 2019-12-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassi', models.CharField(max_length=17)),
                ('nome_do_veiculo', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=20)),
                ('portas', models.CharField(max_length=2)),
            ],
        ),
    ]
